apiVersion: apps/v1
kind: Deployment
metadata:
  name: gowtham-bankapp
  labels:
    app: gowtham-bankapp
spec:
  replicas: 3
  selector:
    matchLabels:
      app: gowtham-bankapp
  template:
    metadata:
      labels:
        app: gowtham-bankapp
    spec:
      containers:
      - name: gowtham-bankapp-container
        image: gowthamk3543/bankapp
        ports:
        - containerPort: 8082
---
apiVersion: v1
kind: Service
metadata:
  name: gowtham-bankapp-service
  labels:
    app: gowtham-bankapp
spec:
  selector:
    app: gowtham-bankapp

  type: NodePort
  ports:
  - nodePort: 31030  
    port: 8082
    targetPort: 8082
